### ISSUE TITLE
News keine Sortierung

### ISSUE THREAD

**Issue by HamburgerJungeJr** [dcngmbh/moox_news#1]
Ich habe seit einigen Tagen ein seltsames Verhalten von den News. 

Ich habe keine Updates durchgeführt, aber plötzlich funktioniert die Sortierung der News nicht mehr. 
Weder im Backend noch im Frontend.(Weder nach Datum noch nach Zuletzt geändert oder nach Titel) Top-News werden allerdings weiterhin ganz oben angezeigt.

Wenn ich über phpMyAdmin die Tabelle sortiere, funktioniert alles. Daher ist das Datum richtig eingetragen.

Woran kann das liegen?

**Comment by jakub-czyz** [comment]
Hallo HamburgerJungeJr,
welche Version von News verwendest du? Unsere extensions in TYPO3 Repository sind zurzeit nicht aktuell, von dem her könntest du mal die Version hier aus dem Github versuchen. Da hat sich jetzt schon wieder viel verändert und es ist mittlerweile möglich auch Ajax News zu nutzen ;-) 

Das wäre jetzt der einzige Tipp den ich dir auf die schnelle geben kann, aber wir prüfen die Sortierungs Funktion im Laufe der nächste Woche.

**Comment by HamburgerJungeJr** [comment]
Vielen Dank für die Antwort,
leider gibt es mit der neuen Version auch keine Veränderung. (0.9.9).
News-Modul
![news](https://cloud.githubusercontent.com/assets/11501266/8761474/6cc49dd8-2d53-11e5-9d35-a49326e5cca4.PNG)

Plugin-Konfiguration
![konfiguration](https://cloud.githubusercontent.com/assets/11501266/8761487/ff41b8c6-2d53-11e5-9b83-b5a56939669b.PNG)

Website-Ausgabe
![website](https://cloud.githubusercontent.com/assets/11501266/8761488/ff42e6f6-2d53-11e5-8d91-986efd1a847a.PNG)

**Comment by HamburgerJungeJr** [comment]
Ich habe mir nochmal die Datenbank angesehen. Anscheinend wird nur nach dem Erstellungsdatum sortiert.

**Comment by jakub-czyz** [comment]
Sorry für die verspätete Antwort. 
Leider können wir das Problem nicht reproduzieren. Wir haben auch den Code geprüft und festgestellt, dass im BE/FE das Feld datetime verwendet wird. Die einzige Idee wäre noch die aktuellste Version (0.9.11) aus Github zu nehmen und danach den typo3temp Ordner manuell leeren.
